from models import db,puppy,owner,toy
rufus=puppy('Rufus')
fido=puppy('Fido')
db.session.add_all([rufus,fido])
db.session.commit()
print(puppy.query.all())
rufus=puppy.query.filter_by(name='Rufus').first()
print(rufus)
jose=owner('Jose',rufus.id)
toy1=toy('Chew toy',rufus.id)
toy2=toy('Ball',rufus.id)
db.session.add_all([jose,toy1,toy2])
db.session.commit()
rufus=puppy.query.filter_by(name='Rufus').first()
print(rufus)
print(rufus.report_toys())
